language: java
install: true

script:
- git config --local user.name "Travis CI"
- git config --local user.email "builds@travis-ci.com"
- git checkout -f master
- mvn -B release:prepare -DskipTests=true -DscmCommentPrefix="[ci skip][maven-release-plugin]" -Dusername=${GITHUB_USERNAME} -Dpassword=${GITHUB_TOKEN}
before_deploy:
- export TAG=$(git describe --tags --abbrev=0)
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Dt0LxLAT1ZGsHHZljahG1I3N1VZCvza2DPvkP+V4Rp55AL/T/atuy/N7zwbX11waAkABylTG96TPKrUHosmFgZGBm1WX3141KKphvhi31r2eu1tGozcuSMlrEQVLtoPOtCHce03pygZkDzLeSmWe+Y3qYuUX2mrS+F6OljH2VT5DjmG/fY1JGdsc5J5ESLLGvEc4CAMuyGWIHKAa1+3w1bgnVF/bftkhKhpe8OhFpcYtNFOo3Q9dq+c2SntItjO4w1OZid1gF0fLY7jZc1Wh/CcIHUu6CEUviQpMe2ydTUVueYU9sDUpE0YXRcR2QD37n8ay4fSNnV/34OpVcnck+m5Egw5CaVx8oNKphsy1giZxk0YomVxKMvLJjduSloYZR6lYpW/byPk6zeXoeVxJnOHgtb4gwYCW9y9S0QmvR5bL0CYI2uX0gvPZTTtc7vsGNTlO3pPA/lU5cUS+TQ7/81Ljqvon3FF3c66+0lTRbJCQQbWEvsdMwQN3McJbV5Qt4CevsgNj2ba0ZlNChN9s/A21SYj/kOAKVqUnCktOzb4RZy8A5Dpn77jEQ/fn9jEmSXmGDwIeehGbUdmKv199lE8Dvtp2eT4WQ/jW7u3MwrBaEb1+6LkkuWPGK3zHbykKAxqnT8PsHQ7zXVjY/vh4InOXnwNfnqRIahbLe0fJmOs=
  tag_name: $TAG
  file: target/$TAG.jar
  on:
    repo: kwoding/sonar-webdriver-plugin
  name: $TAG
branches:
  only:
  - master
